const productos = [
  {
    id: 1,
    nombre: "Champú Revitalizante",
    precio: 5000,
    descripcion: "Champú para cabello seco y dañado, con vitaminas.",
    foto: "https://tse1.mm.bing.net/th?id=OIP.HePb_dsSkw-ZEuKf26UaoAHaHa&pid=Api&P=0&h=180",
  },
  {
    id: 2,
    nombre: "Acondicionador Suavizante",
    precio: 4500,
    descripcion: "Acondicionador que nutre y suaviza el cabello.",
    foto: "https://tse2.mm.bing.net/th?id=OIP.6HwJg_aADu_5R7ZD2XD5jgHaHa&pid=Api&P=0&h=180",
  },
  {
    id: 3,
    nombre: "Gel Fijador",
    precio: 3000,
    descripcion: "Gel de fijación fuerte, ideal para peinados duraderos.",
    foto: "https://tse3.mm.bing.net/th?id=OIP.0hAiwMDwi77GMRoLcdRNYgHaHa&pid=Api&P=0&h=180",
  },
  {
    id: 4,
    nombre: "Cera para Cabello",
    precio: 3500,
    descripcion: "Cera moldeadora para estilos definidos y naturales.",
    foto: "https://co.images.search.yahoo.com/images/view;_ylt=AwrFY1kBMSBnyuMNh9Ktcgx.;_ylu=c2VjA3NyBHNsawNpbWcEb2lkA2JkZmZkNjY3ZmIzZmQ2MzdkY2YwMTQ4MTU1ZTFlNTk4BGdwb3MDMgRpdANiaW5n?back=https%3A%2F%2Fco.images.search.yahoo.com%2Fsearch%2Fimages%3Fp%3DCera%2Bpara%2BCabello%26ei%3DUTF-8%26type%3DE210CO91215G0%26fr%3Dmcafee%26fr2%3Dp%253As%252Cv%253Ai%252Cm%253Asb-top%26tab%3Dorganic%26ri%3D2&w=1200&h=744&imgurl=www.mejoresdispositivos.es%2Fwp-content%2Fuploads%2F2018%2F07%2F5bilde-25-e1531516731249.jpg&rurl=https%3A%2F%2Fwww.mejoresdispositivos.es%2Fcera-para-el-pelo%2F&size=151KB&p=Cera+para+Cabello&oid=bdffd667fb3fd637dcf0148155e1e598&fr2=p%3As%2Cv%3Ai%2Cm%3Asb-top&fr=mcafee&tt=Los+5+Mejores+ceras+para+el+pelo+%28Comparativa+2024%29&b=0&ni=140&no=2&ts=&tab=organic&sigr=jmR6pUx0zjW2&sigb=zHOfa.c07tuK&sigi=QFJ972buJzeu&sigt=oOPrcmsPjDux&.crumb=CbqGuPMS1Nw&fr=mcafee&fr2=p%3As%2Cv%3Ai%2Cm%3Asb-top&type=E210CO91215G0",
  },
  {
    id: 5,
    nombre: "Spray de Brillo",
    precio: 6000,
    descripcion: "Spray que aporta brillo y suavidad al cabello.",
    foto: "https://co.images.search.yahoo.com/images/view;_ylt=AwrFaOzuMSBnfZ4Oh2qtcgx.;_ylu=c2VjA3NyBHNsawNpbWcEb2lkA2Q0ZWFlNjRkNGExMDk2NjYyNzUyZjA2ZjllODNjMmNhBGdwb3MDMgRpdANiaW5n?back=https%3A%2F%2Fco.images.search.yahoo.com%2Fsearch%2Fimages%3Fp%3DSpray%2Bde%2BBrillo%26ei%3DUTF-8%26type%3DE210CO91215G0%26fr%3Dmcafee%26fr2%3Dp%253As%252Cv%253Ai%252Cm%253Asb-top%26tab%3Dorganic%26ri%3D2&w=1000&h=1000&imgurl=i5.walmartimages.com.mx%2Fgr%2Fimages%2Fproduct-images%2Fimg_large%2F00750227036068L.jpg&rurl=https%3A%2F%2Fsuper.walmart.com.mx%2Fip%2Fspray-de-brillo-kerashine-con-keratina-y-oleo-de-argan-120-ml%2F00750227036068&size=42KB&p=Spray+de+Brillo&oid=d4eae64d4a1096662752f06f9e83c2ca&fr2=p%3As%2Cv%3Ai%2Cm%3Asb-top&fr=mcafee&tt=Spray+de+brillo+Kerashine+con+keratina+y+oleo+de+arg%C3%A1n+120+ml+%7C+Walmart&b=0&ni=140&no=2&ts=&tab=organic&sigr=0fCtQC2g4ASh&sigb=PtrPEmav_NDx&sigi=Q7xGYR8AKLby&sigt=kZ4idNghWR.K&.crumb=CbqGuPMS1Nw&fr=mcafee&fr2=p%3As%2Cv%3Ai%2Cm%3Asb-top&type=E210CO91215G0",
  },
  {
    id: 6,
    nombre: "Espuma Voluminizadora",
    precio: 5500,
    descripcion: "Espuma ligera que da volumen sin dejar residuos.",
    foto: "",
  },
  {
    id: 7,
    nombre: "Mascarilla Nutritiva",
    precio: 7500,
    descripcion: "Mascarilla intensa para hidratar y nutrir el cabello.",
    foto: "",
  },
  {
    id: 8,
    nombre: "Aceite de Argán",
    precio: 8000,
    descripcion: "Aceite nutritivo para cabello seco y encrespado.",
    foto: "",
  },
  {
    id: 9,
    nombre: "Cepillo Desenredante",
    precio: 2000,
    descripcion:
      "Cepillo que evita el tirón, ideal para todo tipo de cabellos.",
    foto: "",
  },
  {
    id: 10,
    nombre: "Peine de Precisión",
    precio: 1500,
    descripcion: "Peine fino, perfecto para seccionar el cabello.",
    foto: "",
  },
  {
    id: 11,
    nombre: "Laca Fijadora",
    precio: 4000,
    descripcion: "Laca de alta fijación para mantener el peinado intacto.",
    foto: "",
  },
  {
    id: 12,
    nombre: "Crema para Rizos",
    precio: 5000,
    descripcion: "Crema hidratante que define y controla los rizos.",
    foto: "",
  },
  {
    id: 13,
    nombre: "Espuma Definidora",
    precio: 4500,
    descripcion: "Espuma para definir rizos y controlar el frizz.",
    foto: "",
  },
  {
    id: 14,
    nombre: "Sérum Reparador",
    precio: 8500,
    descripcion: "Sérum que repara las puntas abiertas y da brillo.",
    foto: "",
  },
  {
    id: 15,
    nombre: "Protector Térmico",
    precio: 6000,
    descripcion: "Protege el cabello de las altas temperaturas.",
    foto: "",
  },
  {
    id: 16,
    nombre: "Champú Anticaspa",
    precio: 4800,
    descripcion: "Elimina la caspa y limpia profundamente el cuero cabelludo.",
    foto: "",
  },
  {
    id: 17,
    nombre: "Acondicionador Hidratante",
    precio: 4700,
    descripcion: "Acondicionador para cabello seco y maltratado.",
    foto: "",
  },
  {
    id: 18,
    nombre: "Mascarilla Reparadora",
    precio: 7500,
    descripcion: "Repara y nutre en profundidad el cabello.",
    foto: "",
  },
  {
    id: 19,
    nombre: "Gel para Rizos",
    precio: 3200,
    descripcion: "Gel suave que controla el frizz en el cabello rizado.",
    foto: "",
  },
  {
    id: 20,
    nombre: "Aceite de Coco",
    precio: 6000,
    descripcion: "Aceite natural para hidratar y nutrir el cabello.",
    foto: "",
  },
  {
    id: 21,
    nombre: "Champú Voluminizador",
    precio: 5200,
    descripcion: "Champú que da cuerpo y volumen al cabello fino.",
    foto: "",
  },
  {
    id: 22,
    nombre: "Mousse para Cabello",
    precio: 5500,
    descripcion: "Mousse de fijación ligera, ideal para peinados con volumen.",
    foto: "",
  },
  {
    id: 23,
    nombre: "Cera de Peinado",
    precio: 3700,
    descripcion: "Cera para moldear y dar textura al cabello.",
    foto: "",
  },
  {
    id: 24,
    nombre: "Spray Antifrizz",
    precio: 6300,
    descripcion: "Spray que controla el frizz y aporta brillo.",
    foto: "",
  },
  {
    id: 25,
    nombre: "Mascarilla para Rizos",
    precio: 7600,
    descripcion: "Mascarilla específica para el cuidado de rizos.",
    foto: "",
  },
  {
    id: 26,
    nombre: "Peine Antiestático",
    precio: 1400,
    descripcion: "Peine que evita el frizz en el cabello.",
    foto: "",
  },
  {
    id: 27,
    nombre: "Bálsamo Capilar",
    precio: 5900,
    descripcion: "Bálsamo que suaviza y facilita el peinado.",
    foto: "",
  },
  {
    id: 28,
    nombre: "Aceite de Jojoba",
    precio: 8000,
    descripcion: "Aceite nutritivo para cabello y cuero cabelludo.",
    foto: "",
  },
  {
    id: 29,
    nombre: "Cepillo Térmico",
    precio: 4500,
    descripcion: "Cepillo ideal para secado rápido y estilo.",
    foto: "",
  },
  {
    id: 30,
    nombre: "Spray Protector Solar",
    precio: 6700,
    descripcion: "Protege el cabello de los rayos UV.",
    foto: "",
  },
  {
    id: 31,
    nombre: "Crema Alisadora",
    precio: 5300,
    descripcion: "Crema que ayuda a alisar y controlar el cabello.",
    foto: "",
  },
  {
    id: 32,
    nombre: "Gel Humectante",
    precio: 3300,
    descripcion: "Gel hidratante que define sin dejar residuos.",
    foto: "",
  },
  {
    id: 33,
    nombre: "Acondicionador Voluminizador",
    precio: 4700,
    descripcion: "Acondicionador para dar cuerpo y volumen al cabello.",
    foto: "",
  },
  {
    id: 34,
    nombre: "Mascarilla de Keratina",
    precio: 8000,
    descripcion: "Mascarilla que fortalece y reconstruye el cabello.",
    foto: "",
  },
  {
    id: 35,
    nombre: "Spray Desenredante",
    precio: 3900,
    descripcion: "Facilita el peinado, ideal para cabello largo.",
    foto: "",
  },
  {
    id: 36,
    nombre: "Champú Fortificante",
    precio: 5400,
    descripcion: "Fortalece el cabello y reduce su caída.",
    foto: "",
  },
  {
    id: 37,
    nombre: "Acondicionador Antifrizz",
    precio: 5000,
    descripcion: "Reduce el frizz y mantiene el cabello suave.",
    foto: "",
  },
  {
    id: 38,
    nombre: "Espuma Texturizadora",
    precio: 5800,
    descripcion: "Da cuerpo y textura al cabello sin endurecer.",
    foto: "",
  },
  {
    id: 39,
    nombre: "Laca Suave",
    precio: 4200,
    descripcion: "Laca de fijación suave para peinados naturales.",
    foto: "",
  },
  {
    id: 40,
    nombre: "Serum Antiencrespamiento",
    precio: 8700,
    descripcion: "Controla el encrespamiento y da brillo intenso.",
    foto: "",
  },
];
