const productos = [
  {
    id: 1,
    nombre: "Champú Revitalizante",
    precio: 400,
    descripcion: "Champú para cabello seco y dañado, con vitaminas.",
    foto: "https://tse1.mm.bing.net/th?id=OIP.HePb_dsSkw-ZEuKf26UaoAHaHa&pid=Api&P=0&h=180",
    categoria: "champús",
    tipo: "cuidado capilar",
    marca: "kerzon",
  },
  {
    id: 2,
    nombre: "Acondicionador Suavizante",
    precio: 4500,
    descripcion: "Acondicionador que nutre y suaviza el cabello.",
    foto: "https://tse2.mm.bing.net/th?id=OIP.6HwJg_aADu_5R7ZD2XD5jgHaHa&pid=Api&P=0&h=180",
    categoria: "acondicionadores",
    tipo: "cuidado capilar",
    marca: "Argan",
  },
  {
    id: 3,
    nombre: "Gel Fijador",
    precio: 300,
    descripcion: "Gel de fijación fuerte, ideal para peinados duraderos.",
    foto: "https://tse3.mm.bing.net/th?id=OIP.0hAiwMDwi77GMRoLcdRNYgHaHa&pid=Api&P=0&h=180",
    categoria: "geles",
    tipo: "estilización",
    marca: "everynit",
  },
  {
    id: 4,
    nombre: "Cera para Cabello",
    precio: 3500,
    descripcion: "Cera moldeadora para estilos definidos y naturales.",
    foto: "https://tse1.mm.bing.net/th?id=OIP.2-Q89qLeJButi7haPWoMAAHaHa&pid=Api&P=0&h=180",
    categoria: "ceras",
    tipo: "estilización",
    marca: "Berracuda",
  },
  {
    id: 5,
    nombre: "Spray de Brillo",
    precio: 600,
    descripcion: "Spray que aporta brillo y suavidad al cabello.",
    foto: "https://tse1.mm.bing.net/th?id=OIP.fLTkjb0V-tJUdXQaQfs_qAAAAA&pid=Api&P=0&h=180",
    categoria: "sprays",
    tipo: "acabado",
    marca: "king",
  },
  {
    id: 6,
    nombre: "Espuma Voluminizadora",
    precio: 550,
    descripcion: "Espuma ligera que da volumen sin dejar residuos.",
    foto: "https://tse1.mm.bing.net/th?id=OIP.iq39WoZm9F63INUUZFTBCgHaHa&pid=Api&P=0&h=180",
    categoria: "espumas",
    tipo: "estilización",
    marca: "elayan",
  },
  {
    id: 7,
    nombre: "Mascarilla Nutritiva",
    precio: 7500,
    descripcion: "Mascarilla intensa para hidratar y nutrir el cabello.",
    foto: "https://tse3.mm.bing.net/th?id=OIP.595XwIhrL7R0uphYIIzqtgHaHa&pid=Api&P=0&h=180",
    categoria: "mascarillas",
    tipo: "cuidado capilar",
    marca: "urnier",
  },
  {
    id: 8,
    nombre: "Aceite de Argán",
    precio: 8000,
    descripcion: "Aceite nutritivo para cabello seco y encrespado.",
    foto: "https://tse1.mm.bing.net/th?id=OIP.fhG9lcpACGp-sXRDsM2RgAHaHa&pid=Api&P=0&h=180",
    categoria: "aceites",
    tipo: "cuidado capilar",
    marca: "Argan",
  },
  {
    id: 9,
    nombre: "Cepillo Desenredante",
    precio: 2000,
    descripcion:
      "Cepillo que evita el tirón, ideal para todo tipo de cabellos.",
    foto: "https://tse4.mm.bing.net/th?id=OIP.ziG1FWSDmrHZZhaEupuiWgHaHa&pid=Api&P=0&h=180",
    categoria: "cepillos",
    tipo: "accesorio",
    marca: "breo",
  },
  {
    id: 10,
    nombre: "Peine de Precisión",
    precio: 1500,
    descripcion: "Peine fino, perfecto para seccionar el cabello.",
    foto: "https://tse3.mm.bing.net/th?id=OIP.udgjGL5PhM5YxNWXz6vStQHaHa&pid=Api&P=0&h=180",
    categoria: "peines",
    tipo: "accesorio",
    marca: "liker",
  },
  {
    id: 11,
    nombre: "Laca Fijadora",
    precio: 4000,
    descripcion: "Laca de alta fijación para mantener el peinado intacto.",
    foto: "https://tse3.mm.bing.net/th?id=OIP.mfaC9zU7W4iNYjQhw-_1oQHaHa&pid=Api&P=0&h=180",
    categoria: "lacas",
    tipo: "estilización",
    marca: "fixer",
  },
  {
    id: 12,
    nombre: "Crema para Rizos",
    precio: 5000,
    descripcion: "Crema hidratante que define y controla los rizos.",
    foto: "https://tse3.mm.bing.net/th?id=OIP.YcIxNI-pr-GUJmMDYhsgtwHaHa&pid=Api&P=0&h=180",
    categoria: "cremas",
    tipo: "cuidado capilar",
    marca: "Pantene",
  },
  {
    id: 13,
    nombre: "Espuma Definidora",
    precio: 4500,
    descripcion: "Espuma para definir rizos y controlar el frizz.",
    foto: "https://tse2.mm.bing.net/th?id=OIP.9Sgv1rFDriLK-d4if4EpCQHaHa&pid=Api&P=0&h=180",
    categoria: "espumas",
    tipo: "estilización",
    marca: "canva",
  },
  {
    id: 14,
    nombre: "Sérum Reparador",
    precio: 8500,
    descripcion: "Sérum que repara las puntas abiertas y da brillo.",
    foto: "https://tse2.mm.bing.net/th?id=OIP.fiu8G_fd62bz1JDTv4H6IwHaHa&pid=Api&P=0&h=180",
    categoria: "serums",
    tipo: "cuidado capilar",
    marca: "sensil",
  },
  {
    id: 15,
    nombre: "Protector Térmico",
    precio: 6000,
    descripcion: "Protege el cabello de las altas temperaturas.",
    foto: "https://tse1.mm.bing.net/th?id=OIP.i68jJ2i6j_CQaTJwGmQ2oAHaLE&pid=Api&P=0&h=180",
    categoria: "protectores",
    tipo: "cuidado capilar",
    marca: "prou",
  },
  {
    id: 16,
    nombre: "Champú Anticaspa",
    precio: 4800,
    descripcion: "Elimina la caspa y limpia profundamente el cuero cabelludo.",
    foto: "https://tse3.mm.bing.net/th?id=OIP.6rmYyEmRswz7Vq6y209OeQHaHa&pid=Api&P=0&h=180",
    categoria: "champús",
    tipo: "cuidado capilar",
    marca: "Savital",
  },
  {
    id: 17,
    nombre: "Acondicionador Hidratante",
    precio: 4700,
    descripcion: "Acondicionador para cabello seco y maltratado.",
    foto: "https://tse2.mm.bing.net/th?id=OIP.poxDu9QPb_Y9iNYUXQLqdQHaHa&pid=Api&P=0&h=180",
    categoria: "acondicionadores",
    tipo: "cuidado capilar",
    marca: "hostacuion",
  },
  {
    id: 18,
    nombre: "Mascarilla Reparadora",
    precio: 7500,
    descripcion: "Repara y nutre en profundidad el cabello.",
    foto: "https://tse3.mm.bing.net/th?id=OIP.fXHUOBbvr6KGaiDlB7G6IgHaHa&pid=Api&P=0&h=180",
    categoria: "mascarillas",
    tipo: "cuidado capilar",
    marca: "oreal",
  },
  {
    id: 19,
    nombre: "Gel para Rizos",
    precio: 3200,
    descripcion: "Gel suave que controla el frizz en el cabello rizado.",
    foto: "https://tse3.mm.bing.net/th?id=OIP.Faov02twygcg97s_tt596wAAAA&pid=Api&P=0&h=180",
    categoria: "geles",
    tipo: "estilización",
    marca: "eco",
  },
  {
    id: 20,
    nombre: "Aceite de Coco",
    precio: 6000,
    descripcion: "Aceite natural para hidratar y nutrir el cabello.",
    foto: "https://tse1.mm.bing.net/th?id=OIP.phQNgcRlpp3cP_i3PJ0pHwHaEK&pid=Api&P=0&h=180",
    categoria: "aceites",
    tipo: "cuidado capilar",
    marca: "brayl",
  },
  {
    id: 21,
    nombre: "Champú Voluminizador",
    precio: 5200,
    descripcion: "Champú que da cuerpo y volumen al cabello fino.",
    foto: "https://tse4.mm.bing.net/th?id=OIP.Pv_hA0qWjL5KXNM1u8wjbwHaHa&pid=Api&P=0&h=180",
    categoria: "champús",
    tipo: "cuidado capilar",
    marca: "org",
  },
  {
    id: 22,
    nombre: "Mousse para Cabello",
    precio: 5500,
    descripcion: "Mousse de fijación ligera, ideal para peinados con volumen.",
    foto: "https://spaathome.info/wp-content/uploads/2022/09/CREMA-NUTRITIVA-DE-NOCHE-PARA-PIELES-MADURAS-300x300.jpeg",
    categoria: "mousses",
    tipo: "estilización",
    marca: "blakin",
  },
  {
    id: 23,
    nombre: "Cera de Peinado",
    precio: 3700,
    descripcion: "Cera para moldear y dar textura al cabello.",
    foto: "https://tse3.mm.bing.net/th?id=OIP.wjAFjbW22qFNXp0oE5NMSwHaHa&pid=Api&P=0&h=180",
    categoria: "ceras",
    tipo: "estilización",
    marca: "isana",
  },
  {
    id: 24,
    nombre: "Spray Antifrizz",
    precio: 6300,
    descripcion: "Spray que controla el frizz y aporta brillo.",
    foto: "https://tse1.mm.bing.net/th?id=OIP.nMN0shm0-lARnArfTsNLnAAAAA&pid=Api&P=0&h=180",
    categoria: "sprays",
    tipo: "acabado",
    marca: "pantene",
  },
  {
    id: 25,
    nombre: "Mascarilla para Rizos",
    precio: 7600,
    descripcion: "Mascarilla específica para el cuidado de rizos.",
    foto: "https://tse2.mm.bing.net/th?id=OIP.8zYxjSPlSWJ9KJkAuLEJbAHaHa&pid=Api&P=0&h=180",
    categoria: "mascarillas",
    tipo: "cuidado capilar",
    marca: "confer",
  },
  {
    id: 26,
    nombre: "Peine Antiestático",
    precio: 1400,
    descripcion: "Peine que evita el frizz en el cabello.",
    foto: "https://images-na.ssl-images-amazon.com/images/I/81alGbZHu1L.__AC_SY300_QL70_ML2_.jpg",
    categoria: "peines",
    tipo: "accesorio",
    marca: "ney",
  },
  {
    id: 27,
    nombre: "Bálsamo Capilar",
    precio: 5900,
    descripcion: "Bálsamo que suaviza y facilita el peinado.",
    foto: "https://tse3.mm.bing.net/th?id=OIP.hTjRKiNwYxG6fQWJzFMuFwHaHa&pid=Api&P=0&h=180",
    categoria: "bálsamos",
    tipo: "cuidado capilar",
    marca: "niku",
  },
  {
    id: 28,
    nombre: "Aceite de Jojoba",
    precio: 8000,
    descripcion: "Aceite nutritivo para cabello y cuero cabelludo.",
    foto: "https://tse4.mm.bing.net/th?id=OIP.yumUgQHM7-LUzT_SKyKKRAHaHa&pid=Api&P=0&h=180",
    categoria: "aceites",
    tipo: "cuidado capilar",
    marca: "over",
  },
  {
    id: 29,
    nombre: "Cepillo Térmico",
    precio: 4500,
    descripcion: "Cepillo ideal para secado rápido y estilo.",
    foto: "https://images-na.ssl-images-amazon.com/images/I/61E8PsfqzJL.__AC_SX300_SY300_QL70_ML2_.jpg",
    categoria: "cepillos",
    tipo: "accesorio",
    marca: "everin",
  },
  {
    id: 30,
    nombre: "Spray Protector Solar",
    precio: 6700,
    descripcion: "Protege el cabello de los rayos UV.",
    foto: "https://whatthe-health.com/admin/wp-content/uploads/2023/06/Protector-solar-SPRAY-300x300-1.jpg",
    categoria: "sprays",
    tipo: "acabado",
    marca: "stylin",
  },
  {
    id: 31,
    nombre: "Crema Alisadora",
    precio: 5300,
    descripcion: "Crema que ayuda a alisar y controlar el cabello.",
    foto: "https://tse3.mm.bing.net/th?id=OIP.u9fclF_knp9OCKeMSOxW5AHaHa&pid=Api&P=0&h=180",
    categoria: "cremas",
    tipo: "cuidado capilar",
    marca: "relaxer",
  },
  {
    id: 32,
    nombre: "Gel Humectante",
    precio: 3300,
    descripcion: "Gel hidratante que define sin dejar residuos.",
    foto: "https://tse4.mm.bing.net/th?id=OIP.Od_yP5mwDG5YnRHAamG-pQAAAA&pid=Api&P=0&h=180",
    categoria: "geles",
    tipo: "estilización",
    marca: "buer",
  },
  {
    id: 33,
    nombre: "Acondicionador Voluminizador",
    precio: 4700,
    descripcion: "Acondicionador para dar cuerpo y volumen al cabello.",
    foto: "https://tse2.mm.bing.net/th?id=OIP.fmVv4g7Ihrsxl9KCGAcNxwHaTP&pid=Api&P=0&h=180",
    categoria: "acondicionadores",
    tipo: "cuidado capilar",
    marca: "loreal",
  },
  {
    id: 34,
    nombre: "Mascarilla de Keratina",
    precio: 8000,
    descripcion: "Mascarilla que fortalece y reconstruye el cabello.",
    foto: "https://tse2.mm.bing.net/th?id=OIP.fGVBrmYCNniV80EPldX4rgHaHa&pid=Api&P=0&h=180",
    categoria: "mascarillas",
    tipo: "cuidado capilar",
    marca: "garnier",
  },
  {
    id: 35,
    nombre: "Spray Desenredante",
    precio: 3900,
    descripcion: "Facilita el peinado, ideal para cabello largo.",
    foto: "https://tse4.mm.bing.net/th?id=OIP.P8de1ZamU2fmwUBbVyWtBgHaHa&pid=Api&P=0&h=180",
    categoria: "sprays",
    tipo: "acabado",
    marca: "fullki",
  },
  {
    id: 36,
    nombre: "Champú Fortificante",
    precio: 5400,
    descripcion: "Fortalece el cabello y reduce su caída.",
    foto: "https://www.piubellashop.com/wp-content/uploads/2017/07/CHAMPU-CHOCOTERAPIA-VOLTAGE-1-300x300-1.jpg",
    categoria: "champús",
    tipo: "cuidado capilar",
    marca: "treen",
  },
  {
    id: 37,
    nombre: "Acondicionador Antifrizz",
    precio: 5000,
    descripcion: "Reduce el frizz y mantiene el cabello suave.",
    foto: "https://tse1.mm.bing.net/th?id=OIP.4MfFxIw0kjzQU7C7ivre6gHaHa&pid=Api&P=0&h=180",
    categoria: "acondicionadores",
    tipo: "cuidado capilar",
    marca: "blue",
  },
  {
    id: 38,
    nombre: "Espuma Texturizadora",
    precio: 5800,
    descripcion: "Da cuerpo y textura al cabello sin endurecer.",
    foto: "https://tse2.mm.bing.net/th?id=OIP.JCNNAIGlLrdVYXmTsiWVkwAAAA&pid=Api&P=0&h=180",
    categoria: "espumas",
    tipo: "estilización",
    marca: "neyki",
  },
  {
    id: 39,
    nombre: "Laca Suave",
    precio: 4200,
    descripcion: "Laca de fijación suave para peinados naturales.",
    foto: "https://tse1.mm.bing.net/th?id=OIP.C94RwxS5J4OiBfh1TojrRAAAAA&pid=Api&P=0&h=180",
    categoria: "lacas",
    tipo: "estilización",
    marca: "calink",
  },
  {
    id: 40,
    nombre: "Serum Antiencrespamiento",
    precio: 8700,
    descripcion: "Controla el encrespamiento y da brillo intenso.",
    foto: "https://tse4.mm.bing.net/th?id=OIP.CH_7kz7zNArQkxbbWSi2CgAAAA&pid=Api&P=0&h=180",
    categoria: "serums",
    tipo: "cuidado capilar",
    marca: "mers",
  },
];
